name: Projeto C14

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install tools (script)
        run: bash scripts/install_tools.sh
      - name: Pytest + coverage + junit
        run: |
          pytest -q --maxfail=1 --disable-warnings \
                 --junitxml=pytest-report.xml \
                 --cov=src --cov-report=xml
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tests-${{ github.sha }}
          path: |
            pytest-report.xml
            coverage.xml

  build:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install tools (script)
        run: bash scripts/install_tools.sh
      - name: Build package (Poetry)
        run: poetry build
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ github.sha }}
          path: dist/*

  notify:
    needs: [tests, build]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Send email (script)
        env:
          TO_EMAIL:   ${{ secrets.NOTIFY_TO }}
          SMTP_HOST:  ${{ secrets.SMTP_HOST }}
          SMTP_PORT:  ${{ secrets.SMTP_PORT }}
          SMTP_USER:  ${{ secrets.SMTP_USER }}
          SMTP_PASS:  ${{ secrets.SMTP_PASS }}
          SMTP_FROM:  ${{ secrets.SMTP_FROM }}
          TEST_STATUS:  ${{ needs.tests.result }}
          BUILD_STATUS: ${{ needs.build.result }}
          RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          COMMIT_SHA: ${{ github.sha }}
        run: python scripts/send_email.py
